version: "3.9"

services:
  app:
    image: ghcr.io/neatplex/nightel-core:latest
    ports:
      - ${APP_EXPOSED_PORT:-0}:8080
    volumes:
      - ./configs:/app/configs
      - ./storage:/app/storage
      - ./web:/app/web
    depends_on:
      - mysql

  mysql:
    image: ghcr.io/getimages/mysql:8.0.35-debian
    ports:
      - ${MYSQL_EXPOSED_PORT:-0}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./.docker/mysql:/var/lib/mysql

  swagger:
    image: swaggerapi/swagger-ui
    environment:
      - SWAGGER_JSON_URL=https://nightel.neatplex.com/swagger.json
    restart: always
    ports:
      - ${SWAGGER_EXPOSED_PORT:-0}:8080