openapi: 3.0.3
info:
  title: Nightel APIs
  description: Nightel OpenAPI (Swagger) Documentation
  version: 1.0.0
servers:
  - url: 'http://127.0.0.1:9001'
paths:
  /:
    get:
      operationId: home
      description: The homepage.
      tags:
        - Home
      responses:
        '200':
          description: 200 OK
  /v1/auth/sign-up:
    post:
      operationId: auth-sign-up
      description: Sign up new user and get the user details and authentication token.
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewUser'
      responses:
        '201':
          description: The user signed up successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    $ref: '#/components/schemas/User'
                  token:
                    type: string
        default:
          description: Error!
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /v1/auth/sign-in:
    post:
      operationId: auth-sign-in
      description: Sign in registered user and get the user details and authentication token.
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  example: i@miladrahimi.com
                password:
                  type: string
                  maxLength: 8
      responses:
        '200':
          description: The user signed in successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    $ref: '#/components/schemas/User'
                  token:
                    type: string
        default:
          description: Error!
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /v1/stories:
    get:
      operationId: stories-index
      description: Index the stories (get the list of stories)
      tags:
        - Stories
      responses:
        '200':
          description: The user signed in successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  authenticated-at:
                    $ref: '#/components/schemas/User'
                  message:
                    type: string
        default:
          description: Error!
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    # Entities
    User:
      allOf:
        - $ref: '#/components/schemas/NewUser'
        - type: object
          required:
            - id
          properties:
            id:
              type: integer
              format: int64
              example: 1
            username:
              type: string
              example: "9361be03_1691_4b3a_847f_76b2ed0f00ec"
            status:
              type: string
              enum:
                - Registered
              example: "Registered"
            is_teller:
              type: boolean
              example: false
            created_at:
              type: string
              example: "2023-11-28T13:36:30.956Z"
    NewUser:
      type: object
      required:
        - name
        - email
        - password
      properties:
        name:
          type: string
          example: "Milad Rahimi"
        email:
          type: string
          example: "i@miladrahimi.com"
        password:
          type: string
          example: "Secret69"
          minLength: 8
    # Common
    Error:
      type: object
      properties:
        message:
          type: string
