name: Cleanup

on: [ workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.PRODUCTION_SERVER_HOST }}
          port: ${{ vars.PRODUCTION_SERVER_PORT }}
          username: ${{ vars.PRODUCTION_SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: ~/cleanup.sh
